import Head from "next/head";
import React, { Component } from "react";
import { Container } from 'reactstrap';
import Section from "../components/EAuth/section";
import About from "../components/EAuth/About";
import Testi from "../components/EAuth/Testi";
import Partners from '../components/Shared/Partners';
import Blog from "../components/EAuth/Blog";
import Footer from "../components/Layout/Footer";
import Topbar from "../components/Layout/Topbar";
//Render Components

class payment extends Component {
  componentDidMount() {
    document.body.classList = "";
    document.getElementById("topnav")?.classList.add("bg-white");
    window.addEventListener("scroll", this.scrollNavigation, true);
  }
  // Make sure to remove the DOM listener when the component is unmounted.
  componentWillUnmount() {
    window.removeEventListener("scroll", this.scrollNavigation, true);
  }

  scrollNavigation = () => {
    var doc = document.documentElement;
    var top = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);
    if (top > 80) {
      document.getElementById("topnav")?.classList.add("nav-sticky");
    } else {
      document.getElementById("topnav")?.classList.remove("nav-sticky");
    }
  };
  render() {
    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          <Topbar />
           {/* Hero Start */}
           <Section/>

{/* About */}
<About />

{/* Testi */}
<Testi />

{/* Partner */}
<section className="pt-5 pb-5 border-bottom border-top">
    <Container>
        <Partners />
    </Container>
</section>

{/* Blog */}
<Blog />

          <Footer />
        </main>
      </div>
    );
  }
}

export default payment;
