import Head from "next/head";
import React, { Component } from "react";
import Footer from "../components/Layout/Footer";
import Topbar from "../components/Layout/Topbar";
import Section from '../components/ElektroPos/section';
import Feature from '../components/ElektroPos/Feature';
import About from '../components/ElektroPos/About';
import Cta from '../components/ElektroPos/Cta';
import Services from '../components/ElektroPos/Services';
import Cta1 from '../components/ElektroPos/Cta1';
import Testi from '../components/ElektroPos/Testi';
import Partners from '../components/Shared/Partners';
import { Container } from 'reactstrap';
//Render Components

class Bitcoin extends Component {

  render() {
    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          <Topbar />
            {/* Hero Start */}
            <Section />  

             {/* Feature */}
                <Feature />

{/* About */}
<About />

 {/* Cta */}
 <Cta />

  {/* Services */}
  <Services />

  {/* Cta1 */}
  <Cta1 />

{/* Testi */}
<Testi />
 {/* Partner */}
 <section className="bg-light section-two">
                    <Container>
                        <Partners />
                    </Container>
                </section>
 
          <Footer />
        </main>
      </div>
    );
  }
}

export default Bitcoin;
